#!/bin/bash
set -euo pipefail

# =============================
# Enhanced Multi-Instance Manager (Universal Hybrid Edition)
# =============================

# Function to display header
display_header() {
    clear
    cat << "EOF"
========================================================================
  __  __ ___ _____ _   _ _       ____  _        _ __   __ _____ 
 |  \/  |_ _|_   _| | | | |     |  _ \| |      / \\ \ / /|___  |
 | |\/| | | | | | | | | | |     | |_) | |     / _ \\ V /    / / 
 | |  | | | | | | | |_| | |___  |  __/| |___ / ___ \| |    / /__
 |_|  |_|___| |_|  \___/|_____| |_|   |_____/_/   \_\_|   /_____|
                                                                        
                        POWERED BY MITUL PLAYZ
========================================================================
EOF
    echo
}

# Function to display colored output
print_status() {
    local type=$1
    local message=$2
    
    case $type in
        "INFO") echo -e "\033[1;34m[INFO]\033[0m $message" ;;
        "WARN") echo -e "\033[1;33m[WARN]\033[0m $message" ;;
        "ERROR") echo -e "\033[1;31m[ERROR]\033[0m $message" ;;
        "SUCCESS") echo -e "\033[1;32m[SUCCESS]\033[0m $message" ;;
        "INPUT") echo -e "\033[1;36m[INPUT]\033[0m $message" ;;
        *) echo "[$type] $message" ;;
    esac
}

# Function to check virtualization capabilities
detect_virtualization() {
    display_header
    print_status "INFO" "Analyzing host system environment specifications..."
    
    # Check if KVM device node exists and CPU virtualization extensions are exposed
    if [ -c /dev/kvm ] && grep -E -q '(vmx|svm)' /proc/cpuinfo; then
        IS_KVM_SUPPORTED=true
        HOST_MODE_LABEL="KVM Hardware Virtualization (LXC VM Mode)"
        print_status "SUCCESS" "Hardware virtualization detected. Utilizing High-Performance Isolated VMs."
    else
        IS_KVM_SUPPORTED=false
        HOST_MODE_LABEL="Non-KVM / Shared Kernel (LXC Container Mode)"
        print_status "WARN" "KVM hardware virtualization not available."
        print_status "INFO" "Fallback active: Utilizing Lightweight Shared-Kernel System Containers."
    fi
    sleep 2
}

# Function to validate input
validate_input() {
    local type=$1
    local value=$2
    
    case $type in
        "number")
            if ! [[ "$value" =~ ^[0-9]+$ ]]; then
                print_status "ERROR" "Must be a number"
                return 1
            fi
            ;;
        "size")
            if ! [[ "$value" =~ ^[0-9]+[GgMm]$ ]]; then
                print_status "ERROR" "Must be a size with unit (e.g., 100G, 512M)"
                return 1
            fi
            ;;
        "port")
            if ! [[ "$value" =~ ^[0-9]+$ ]] || [ "$value" -lt 23 ] || [ "$value" -gt 65535 ]; then
                print_status "ERROR" "Must be a valid port number (23-65535)"
                return 1
            fi
            ;;
        "name")
            if ! [[ "$value" =~ ^[a-zA-Z0-9_-]+$ ]]; then
                print_status "ERROR" "Name can only contain letters, numbers, hyphens, and underscores"
                return 1
            fi
            ;;
        "username")
            if ! [[ "$value" =~ ^[a-z_][a-z0-9_-]*$ ]]; then
                print_status "ERROR" "Username must start with a letter/underscore, and contain lowercase alphanumeric characters"
                return 1
            fi
            ;;
    esac
    return 0
}

# Function to check dependencies
check_dependencies() {
    local deps=("lxc" "openssl")
    local missing_deps=()
    
    for dep in "${deps[@]}"; do
        if ! command -v "$dep" &>/dev/null; then
            missing_deps+=("$dep")
        fi
    done
    
    if [ ${#missing_deps[@]} -ne 0 ]; then
        print_status "ERROR" "Missing dependencies: ${missing_deps[*]}"
        print_status "INFO" "Please install and initialize LXD/Incus on your host machine."
        exit 1
    fi
}

cleanup() {
    :
}

# Function to get all managed profiles
get_vm_list() {
    find "$VM_DIR" -name "*.conf" -exec basename {} .conf \; 2>/dev/null | sort
}

# Function to load managed profile configuration
load_vm_config() {
    local vm_name=$1
    local config_file="$VM_DIR/$vm_name.conf"
    
    if [[ -f "$config_file" ]]; then
        unset VM_NAME OS_TYPE CODENAME LXC_IMAGE HOSTNAME USERNAME PASSWORD
        unset DISK_SIZE MEMORY CPUS SSH_PORT GUI_MODE PORT_FORWARDS CREATED PROVISIONED VM_MODE
        
        source "$config_file"
        # Fallback if config was generated by legacy scripts missing VM_MODE variable
        VM_MODE="${VM_MODE:-container}"
        return 0
    else
        print_status "ERROR" "Configuration for instance '$vm_name' not found"
        return 1
    fi
}

# Function to save managed profile configuration
save_vm_config() {
    local config_file="$VM_DIR/$VM_NAME.conf"
    
    cat > "$config_file" <<EOF
VM_NAME="$VM_NAME"
OS_TYPE="$OS_TYPE"
CODENAME="$CODENAME"
LXC_IMAGE="$LXC_IMAGE"
HOSTNAME="$HOSTNAME"
USERNAME="$USERNAME"
PASSWORD="$PASSWORD"
DISK_SIZE="$DISK_SIZE"
MEMORY="$MEMORY"
CPUS="$CPUS"
SSH_PORT="$SSH_PORT"
GUI_MODE="$GUI_MODE"
PORT_FORWARDS="$PORT_FORWARDS"
CREATED="$CREATED"
PROVISIONED="${PROVISIONED:-false}"
VM_MODE="$VM_MODE"
EOF
    print_status "SUCCESS" "Configuration saved to $config_file"
}

# Function to create and configure a new instance
create_new_vm() {
    print_status "INFO" "Launching deployment engine Setup Wizard..."
    
    print_status "INFO" "Select an OS template to set up:"
    local os_options=()
    local i=1
    for os in "${!OS_OPTIONS[@]}"; do
        echo "  $i) $os"
        os_options[$i]="$os"
        ((i++))
    done
    
    while true; do
        read -p "$(print_status "INPUT" "Enter your choice (1-${#OS_OPTIONS[@]}): ")" choice
        if [[ "$choice" =~ ^[0-9]+$ ]] && [ "$choice" -ge 1 ] && [ "$choice" -le ${#OS_OPTIONS[@]} ]; then
            local os="${os_options[$choice]}"
            IFS='|' read -r OS_TYPE CODENAME LXC_IMAGE DEFAULT_HOSTNAME DEFAULT_USERNAME DEFAULT_PASSWORD <<< "${OS_OPTIONS[$os]}"
            break
        else
            print_status "ERROR" "Invalid selection. Try again."
        fi
    done

    while true; do
        read -p "$(print_status "INPUT" "Enter unique instance name (default: $DEFAULT_HOSTNAME): ")" VM_NAME
        VM_NAME="${VM_NAME:-$DEFAULT_HOSTNAME}"
        if validate_input "name" "$VM_NAME"; then
            if [[ -f "$VM_DIR/$VM_NAME.conf" ]] || lxc info "$VM_NAME" &>/dev/null; then
                print_status "ERROR" "An instance named '$VM_NAME' already exists in your environment configurations."
            else
                break
            fi
        fi
    done

    while true; do
        read -p "$(print_status "INPUT" "Enter internal hostname (default: $VM_NAME): ")" HOSTNAME
        HOSTNAME="${HOSTNAME:-$VM_NAME}"
        if validate_input "name" "$HOSTNAME"; then
            break
        fi
    done

    while true; do
        read -p "$(print_status "INPUT" "Enter non-root system username (default: $DEFAULT_USERNAME): ")" USERNAME
        USERNAME="${USERNAME:-$DEFAULT_USERNAME}"
        if validate_input "username" "$USERNAME"; then
            break
        fi
    done

    while true; do
        read -s -p "$(print_status "INPUT" "Enter login access password (default: $DEFAULT_PASSWORD): ")" PASSWORD
        PASSWORD="${PASSWORD:-$DEFAULT_PASSWORD}"
        echo
        if [ -n "$PASSWORD" ]; then
            break
        else
            print_status "ERROR" "Password cannot be empty"
        fi
    done

    while true; do
        read -p "$(print_status "INPUT" "Virtual disk size limit (default: 20G): ")" DISK_SIZE
        DISK_SIZE="${DISK_SIZE:-20G}"
        if validate_input "size" "$DISK_SIZE"; then
            break
        fi
    done

    while true; do
        read -p "$(print_status "INPUT" "Memory capacity allocation in MB (default: 2048): ")" MEMORY
        MEMORY="${MEMORY:-2048}"
        if validate_input "number" "$MEMORY"; then
            break
        fi
    done

    while true; do
        read -p "$(print_status "INPUT" "Assigned CPU Core Limit count (default: 2): ")" CPUS
        CPUS="${CPUS:-2}"
        if validate_input "number" "$CPUS"; then
            break
        fi
    done

    while true; do
        read -p "$(print_status "INPUT" "SSH Forwarding Port on Host Interface (default: 2222): ")" SSH_PORT
        SSH_PORT="${SSH_PORT:-2222}"
        if validate_input "port" "$SSH_PORT"; then
            if ss -tln 2>/dev/null | grep -q ":$SSH_PORT "; then
                print_status "ERROR" "Port $SSH_PORT is already actively bound on the host machine interface."
            else
                break
            fi
        fi
    done

    GUI_MODE=false
    read -p "$(print_status "INPUT" "Additional custom port forwards mapping (e.g., 8080:80, 9000:9000 or Enter for none): ")" PORT_FORWARDS

    CREATED="$(date)"
    
    # Explicitly track how this specific instance will be launched based on what was detected
    if [ "$IS_KVM_SUPPORTED" = true ]; then
        VM_MODE="vm"
    else
        VM_MODE="container"
    fi
    PROVISIONED="false"

    # Deploy via Universal Engine parameters
    setup_vm_image
    save_vm_config
}

# Function to initialize, size, and provision the LXC framework instance
setup_vm_image() {
    print_status "INFO" "Deploying target image profile utilizing [$VM_MODE] execution structure..."
    
    if ! lxc info "$VM_NAME" &>/dev/null; then
        if [ "$VM_MODE" = "vm" ]; then
            # Initialize with native isolation flag
            if ! lxc init "$LXC_IMAGE" "$VM_NAME" --vm; then
                print_status "ERROR" "Failed to download or initialize execution parameters in Virtual Machine mode."
                exit 1
            fi
        else
            # Initialize lightweight shared kernel profile
            if ! lxc init "$LXC_IMAGE" "$VM_NAME"; then
                print_status "ERROR" "Failed to download or initialize execution parameters in System Container mode."
                exit 1
            fi
        fi
    fi
    
    # Set Allocations
    lxc config set "$VM_NAME" limits.cpu "$CPUS"
    lxc config set "$VM_NAME" limits.memory "${MEMORY}MB"
    
    # Configure root storage bounds
    local formatted_disk_size="$DISK_SIZE"
    if [[ "$formatted_disk_size" =~ [Gg]$ ]]; then
        formatted_disk_size="${formatted_disk_size%[Gg]}GiB"
    elif [[ "$formatted_disk_size" =~ [Mm]$ ]]; then
        formatted_disk_size="${formatted_disk_size%[Mm]}MiB"
    fi
    
    if [ "$VM_MODE" = "vm" ]; then
        lxc config device override "$VM_NAME" root size="$formatted_disk_size"
    else
        lxc config device override "$VM_NAME" root size="$formatted_disk_size" 2>/dev/null || \
        lxc config device set "$VM_NAME" root size="$formatted_disk_size" || true
    fi

    # Bind Cloud-Init configuration profiles
    lxc config set "$VM_NAME" cloud-init.user-data - <<EOF
#cloud-config
hostname: $HOSTNAME
ssh_pwauth: true
disable_root: false
users:
  - name: $USERNAME
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    password: $(openssl passwd -6 "$PASSWORD")
chpasswd:
  list: |
    root:$PASSWORD
    $USERNAME:$PASSWORD
  expire: false
EOF

    # Handle Inbound SSH Host Proxy Routing
    lxc config device remove "$VM_NAME" ssh-proxy &>/dev/null || true
    lxc config device add "$VM_NAME" ssh-proxy proxy listen=tcp:0.0.0.0:$SSH_PORT connect=tcp:127.0.0.1:22

    # Custom external mapped proxy routes string loop
    if [[ -n "$PORT_FORWARDS" ]]; then
        IFS=',' read -ra forwards <<< "$PORT_FORWARDS"
        local idx=1
        for forward in "${forwards[@]}"; do
            IFS=':' read -r host_port guest_port <<< "$forward"
            lxc config device remove "$VM_NAME" "custom-proxy-$idx" &>/dev/null || true
            lxc config device add "$VM_NAME" "custom-proxy-$idx" proxy listen=tcp:0.0.0.0:$host_port connect=tcp:127.0.0.1:$guest_port
            ((idx++))
        done
    fi
    
    print_status "SUCCESS" "LXC instance parameters safely configured."
}

# Function to start an instance
start_vm() {
    local vm_name=$1
    
    if load_vm_config "$vm_name"; then
        print_status "INFO" "Starting $vm_name ($VM_MODE)..."
        lxc start "$vm_name"
        
        print_status "INFO" "Allowing cluster engine network states to stabilize..."
        sleep 5
        
        # In Container Mode, standard images lack Cloud-Init by default. Run runtime command injection fallback.
        if [ "$VM_MODE" = "container" ] && [ "${PROVISIONED:-false}" != "true" ]; then
            print_status "INFO" "First boot processing: Provisioning system users, accounts & OpenSSH daemon layers..."
            
            lxc exec "$vm_name" -- bash -c "
                if command -v apt-get &>/dev/null; then
                    apt-get update && apt-get install -y sudo openssh-server openssl || true
                elif command -v dnf &>/dev/null; then
                    dnf install -y sudo openssh-server openssl || true
                fi
                
                hostnamectl set-hostname '$HOSTNAME' || echo '$HOSTNAME' > /etc/hostname
                
                if ! id -u '$USERNAME' &>/dev/null; then
                    useradd -m -s /bin/bash -G sudo,wheel '$USERNAME' 2>/dev/null || useradd -m -s /bin/bash '$USERNAME'
                fi
                
                echo 'root:$PASSWORD' | chpasswd
                echo '$USERNAME:$PASSWORD' | chpasswd
                echo '$USERNAME ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/$USERNAME && chmod 0440 /etc/sudoers.d/$USERNAME
                
                sed -i 's/#\?PasswordAuthentication.*/PasswordAuthentication yes/g' /etc/ssh/sshd_config
                sed -i 's/#\?PermitRootLogin.*/PermitRootLogin yes/g' /etc/ssh/sshd_config
                systemctl restart sshd || systemctl restart ssh || service ssh restart || true
            " &>/dev/null || true
            
            PROVISIONED="true"
            save_vm_config
        fi
        
        local ip_addr
        ip_addr=$(lxc list "$vm_name" -c 4 --format csv | awk '{print $1}')
        
        print_status "SUCCESS" "$vm_name runtime active."
        print_status "INFO" "Internal NAT IP Lease: ${ip_addr:-Awaiting assignment from bridge...}"
        print_status "INFO" "Connect terminal link via: ssh -p $SSH_PORT $USERNAME@localhost"
        print_status "INFO" "Authentication: $USERNAME / $PASSWORD"
    fi
}

# Function to stop an instance
stop_vm() {
    local vm_name=$1
    if load_vm_config "$vm_name"; then
        print_status "INFO" "Sending clean power-off interrupt string to: $vm_name"
        lxc stop "$vm_name"
        print_status "SUCCESS" "Instance $vm_name completely powered down."
    fi
}

# Function to delete an instance
delete_vm() {
    local vm_name=$1
    
    print_status "WARN" "This action permanently destroys instance filesystem structures for '$vm_name'!"
    read -p "$(print_status "INPUT" "Confirm absolute deletion? (y/N): ")" -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        if load_vm_config "$vm_name"; then
            lxc delete "$vm_name" --force
            rm -f "$VM_DIR/$vm_name.conf"
            print_status "SUCCESS" "Instance metadata cleanly unmounted and deleted."
        fi
    else
        print_status "INFO" "Deletion transaction dropped safely."
    fi
}

# Function to show profile details
show_vm_info() {
    local vm_name=$1
    
    if load_vm_config "$vm_name"; then
        echo
        print_status "INFO" "Properties Sheet: $vm_name"
        echo "=========================================================="
        echo "Architecture Mode:   $VM_MODE"
        echo "Target Distribution: $OS_TYPE ($CODENAME)"
        echo "Remote Stream Index: $LXC_IMAGE"
        echo "Internal Hostname:   $HOSTNAME"
        echo "System Profile User: $USERNAME"
        echo "Profile Password:    $PASSWORD"
        echo "SSH Host Mapped Port:$SSH_PORT"
        echo "Allocated Ram/Memory:$MEMORY MB"
        echo "Assigned CPU Cores:  $CPUS Cores"
        echo "Assigned Disk Quota: $DISK_SIZE"
        echo "Port Mappings Array: ${PORT_FORWARDS:-None Specified}"
        echo "Deployment Timestamp:$CREATED"
        echo "=========================================================="
        echo
        read -p "$(print_status "INPUT" "Press Enter to continue...")"
    fi
}

# Function to check if running
is_vm_running() {
    local vm_name=$1
    if lxc info "$vm_name" 2>/dev/null | grep -q "Status: RUNNING"; then
        return 0
    else
        return 1
    fi
}

# Function to edit configuration
edit_vm_config() {
    local vm_name=$1
    
    if load_vm_config "$vm_name"; then
        print_status "INFO" "Modifying resource allocation matrices: $vm_name"
        
        while true; do
            echo "What would you like to edit?"
            echo "  1) Hostname"
            echo "  2) Username"
            echo "  3) Password"
            echo "  4) SSH Port mapping"
            echo "  5) Port Forwards configuration"
            echo "  6) Memory Allocation (RAM)"
            echo "  7) CPU Core Count"
            echo "  8) Disk Space Scale"
            echo "  0) Return to Dashboard"
            
            read -p "$(print_status "INPUT" "Enter your choice: ")" edit_choice
            
            case $edit_choice in
                1)
                    read -p "$(print_status "INPUT" "Enter new hostname (current: $HOSTNAME): ")" new_hostname
                    HOSTNAME="${new_hostname:-$HOSTNAME}"
                    ;;
                2)
                    read -p "$(print_status "INPUT" "Enter new username (current: $USERNAME): ")" new_username
                    USERNAME="${new_username:-$USERNAME}"
                    ;;
                3)
                    read -p "$(print_status "INPUT" "Enter new password: ")" new_password
                    PASSWORD="${new_password:-$PASSWORD}"
                    ;;
                4)
                    read -p "$(print_status "INPUT" "Enter new SSH mapping port (current: $SSH_PORT): ")" new_ssh_port
                    SSH_PORT="${new_ssh_port:-$SSH_PORT}"
                    ;;
                5)
                    read -p "$(print_status "INPUT" "Port Forwards string (current: ${PORT_FORWARDS:-None}): ")" new_port_forwards
                    PORT_FORWARDS="${new_port_forwards:-$PORT_FORWARDS}"
                    ;;
                6)
                    read -p "$(print_status "INPUT" "Enter Memory Size in MB (current: $MEMORY): ")" new_memory
                    MEMORY="${new_memory:-$MEMORY}"
                    ;;
                7)
                    read -p "$(print_status "INPUT" "Enter CPU Core count (current: $CPUS): ")" new_cpus
                    CPUS="${new_cpus:-$CPUS}"
                    ;;
                8)
                    read -p "$(print_status "INPUT" "Enter Extended Disk Size (current: $DISK_SIZE): ")" new_disk_size
                    DISK_SIZE="${new_disk_size:-$DISK_SIZE}"
                    ;;
                0) return 0 ;;
                *) print_status "ERROR" "Invalid option selection"; continue ;;
            esac
            
            setup_vm_image
            save_vm_config
            
            read -p "$(print_status "INPUT" "Continue adjusting variables? (y/N): ")" continue_editing
            if [[ ! "$continue_editing" =~ ^[Yy]$ ]]; then
                break
            fi
        done
    fi
}

# Function to resize disk allocation
resize_vm_disk() {
    local vm_name=$1
    if load_vm_config "$vm_name"; then
        print_status "INFO" "Current disk footprint configuration: $DISK_SIZE"
        while true; do
            read -p "$(print_status "INPUT" "Enter new destination boundary target format size (e.g., 50G): ")" new_disk_size
            if validate_input "size" "$new_disk_size"; then
                local formatted_size="$new_disk_size"
                if [[ "$formatted_size" =~ [Gg]$ ]]; then
                    formatted_size="${formatted_size%[Gg]}GiB"
                elif [[ "$formatted_size" =~ [Mm]$ ]]; then
                    formatted_size="${formatted_size%[Mm]}MiB"
                fi

                print_status "INFO" "Altering device configuration boundaries inside storage structures..."
                if lxc config device set "$vm_name" root size="$formatted_size" 2>/dev/null || lxc config device override "$vm_name" root size="$formatted_size" 2>/dev/null; then
                    DISK_SIZE="$new_disk_size"
                    save_vm_config
                    print_status "SUCCESS" "Storage parameters extended successfully to $new_disk_size."
                else
                    print_status "WARN" "LXC Storage Driver adjustments logged. Driver constraints may block runtime changes."
                fi
                break
            fi
        done
    fi
}

# Function to show live metrics
show_vm_performance() {
    local vm_name=$1
    if load_vm_config "$vm_name"; then
        if is_vm_running "$vm_name"; then
            print_status "INFO" "Exposing Active Runtime Telemetry: $vm_name"
            echo "=========================================================="
            lxc info "$vm_name"
            echo "=========================================================="
        else
            print_status "INFO" "Target Profile instance structural loop $vm_name is not active."
        fi
        read -p "$(print_status "INPUT" "Press Enter to continue...")"
    fi
}

# Main dashboard interface
main_menu() {
    while true; do
        display_header
        echo -e "Host Capabilities Target Mode: \033[1;35m$HOST_MODE_LABEL\033[0m"
        echo "------------------------------------------------------------------------"
        
        local vms=($(get_vm_list))
        local vm_count=${#vms[@]}
        
        if [ $vm_count -gt 0 ]; then
            print_status "INFO" "Detected $vm_count Managed Environment Profiles:"
            for i in "${!vms[@]}"; do
                local status="Stopped"
                if is_vm_running "${vms[$i]}"; then
                    status="Running"
                fi
                # Load profile momentarily to identify its execution nature (VM vs Container)
                if load_vm_config "${vms[$i]}" &>/dev/null; then
                    printf "  %2d) %s [%s] (%s)\n" $((i+1)) "${vms[$i]}" "$VM_MODE" "$status"
                else
                    printf "  %2d) %s (%s)\n" $((i+1)) "${vms[$i]}" "$status"
                fi
            done
            echo
        fi
        
        echo "Main Control Dashboard Operations:"
        echo "  1) Create a new Instance Profile"
        if [ $vm_count -gt 0 ]; then
            echo "  2) Boot/Start Target Environment Instance"
            echo "  3) Shut down/Stop Instance Target Loop"
            echo "  4) Inspect Profile System configurations"
            echo "  5) Modify Resource Parameters & Limits"
            echo "  6) Destroy/Erase Instance Profile Data"
            echo "  7) Adjust Disk/Storage Volumes Scale"
            echo "  8) Read Metric Diagnostics Data"
        fi
        echo "  0) Exit Script Engine"
        echo
        
        read -p "$(print_status "INPUT" "Enter targeted action menu key: ")" choice
        
        case $choice in
            1) create_new_vm ;;
            2)
                if [ $vm_count -gt 0 ]; then
                    read -p "$(print_status "INPUT" "Start Instance Index: ")" vm_num
                    if [[ "$vm_num" =~ ^[0-9]+$ ]] && [ "$vm_num" -ge 1 ] && [ "$vm_num" -le $vm_count ]; then
                        start_vm "${vms[$((vm_num-1))]}"
                    else
                        print_status "ERROR" "Index range configuration argument invalid."
                    fi
                fi
                ;;
            3)
                if [ $vm_count -gt 0 ]; then
                    read -p "$(print_status "INPUT" "Terminate Instance Index: ")" vm_num
                    if [[ "$vm_num" =~ ^[0-9]+$ ]] && [ "$vm_num" -ge 1 ] && [ "$vm_num" -le $vm_count ]; then
                        stop_vm "${vms[$((vm_num-1))]}"
                    else
                        print_status "ERROR" "Index range configuration argument invalid."
                    fi
                fi
                ;;
            4)
                if [ $vm_count -gt 0 ]; then
                    read -p "$(print_status "INPUT" "Inspect Profile Index: ")" vm_num
                    if [[ "$vm_num" =~ ^[0-9]+$ ]] && [ "$vm_num" -ge 1 ] && [ "$vm_num" -le $vm_count ]; then
                        show_vm_info "${vms[$((vm_num-1))]}"
                    else
                        print_status "ERROR" "Index range configuration argument invalid."
                    fi
                fi
                ;;
            5)
                if [ $vm_count -gt 0 ]; then
                    read -p "$(print_status "INPUT" "Modify Parameters Index: ")" vm_num
                    if [[ "$vm_num" =~ ^[0-9]+$ ]] && [ "$vm_num" -ge 1 ] && [ "$vm_num" -le $vm_count ]; then
                        edit_vm_config "${vms[$((vm_num-1))]}"
                    else
                        print_status "ERROR" "Index range configuration argument invalid."
                    fi
                fi
                ;;
            6)
                if [ $vm_count -gt 0 ]; then
                    read -p "$(print_status "INPUT" "Destroy Target Index: ")" vm_num
                    if [[ "$vm_num" =~ ^[0-9]+$ ]] && [ "$vm_num" -ge 1 ] && [ "$vm_num" -le $vm_count ]; then
                        delete_vm "${vms[$((vm_num-1))]}"
                    else
                        print_status "ERROR" "Index range configuration argument invalid."
                    fi
                fi
                ;;
            7)
                if [ $vm_count -gt 0 ]; then
                    read -p "$(print_status "INPUT" "Target Storage Dimension Index: ")" vm_num
                    if [[ "$vm_num" =~ ^[0-9]+$ ]] && [ "$vm_num" -ge 1 ] && [ "$vm_num" -le $vm_count ]; then
                        resize_vm_disk "${vms[$((vm_num-1))]}"
                    else
                        print_status "ERROR" "Index range configuration argument invalid."
                    fi
                fi
                ;;
            8)
                if [ $vm_count -gt 0 ]; then
                    read -p "$(print_status "INPUT" "Target Metric Diagnostics Index: ")" vm_num
                    if [[ "$vm_num" =~ ^[0-9]+$ ]] && [ "$vm_num" -ge 1 ] && [ "$vm_num" -le $vm_count ]; then
                        show_vm_performance "${vms[$((vm_num-1))]}"
                    else
                        print_status "ERROR" "Index range configuration argument invalid."
                    fi
                fi
                ;;
            0) print_status "INFO" "Exiting Script Engine."; exit 0 ;;
            *) print_status "ERROR" "Selection argument execution mismatch error." ;;
        esac
        
        read -p "$(print_status "INPUT" "Press Enter to return to Dashboard...")"
    done
}

# Core Application Flow Initializations
trap cleanup EXIT
check_dependencies

# Prepare structural storage profile spaces
VM_DIR="${VM_DIR:-$HOME/instances_manager}"
mkdir -p "$VM_DIR"

# Architecture Options Mirror Maps
declare -A OS_OPTIONS=(
    ["Ubuntu 22.04"]="ubuntu|jammy|ubuntu:22.04|ubuntu22|ubuntu|ubuntu"
    ["Ubuntu 24.04"]="ubuntu|noble|ubuntu:24.04|ubuntu24|ubuntu|ubuntu"
    ["Debian 11"]="debian|bullseye|images:debian/11|debian11|debian|debian"
    ["Debian 12"]="debian|bookworm|images:debian/12|debian12|debian|debian"
    ["Fedora 40"]="fedora|40|images:fedora/40|fedora40|fedora|fedora"
    ["CentOS Stream 9"]="centos|stream9|images:centos/9-stream|centos9|centos|centos"
    ["AlmaLinux 9"]="almalinux|9|images:almalinux/9|almalinux9|alma|alma"
    ["Rocky Linux 9"]="rockylinux|9|images:rockylinux/9|rocky9|rocky|rocky"
)

# Fire hardware capability scanners before launching user panels
detect_virtualization
main_menu
